language: bash

env:
  jobs:
    - BUILDX_VERSION=0.4.2 DOCKER_VERSION=test
    - BUILDX_VERSION=0.4.2 DOCKER_VERSION=stable
    - BUILDX_VERSION=0.4.2 DOCKER_VERSION=19.03
    - BUILDX_VERSION=0.4.1 DOCKER_VERSION=test
    - BUILDX_VERSION=0.4.1 DOCKER_VERSION=stable
    - BUILDX_VERSION=0.4.1 DOCKER_VERSION=19.03
    - BUILDX_VERSION=0.4.0 DOCKER_VERSION=test
    - BUILDX_VERSION=0.4.0 DOCKER_VERSION=stable
    - BUILDX_VERSION=0.4.0 DOCKER_VERSION=19.03
    - BUILDX_VERSION=0.3.1 DOCKER_VERSION=test
    - BUILDX_VERSION=0.3.1 DOCKER_VERSION=stable
    - BUILDX_VERSION=0.3.1 DOCKER_VERSION=19.03

services:
  - docker

jobs:
  include:
    - name: build for non master branch
      if: branch != master
      script:
        - make ci-install-buildx
        - make ci-build

    - name: build and push on master branch
      if: branch = master
      script:
        - make ci-install-buildx
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - EXTRA_ARGS=--push make ci-build
